GET http://localhost:5000/api/profile/test

###

POST http://localhost:5000/api/users/register HTTP/1.1
content-type: application/json

{
    "name": "Donatas1",
    "email": "donas1@test.com",
    "password": "test"
}